development: &development
  adapter: postgresql
  encoding: unicode
  database: rental_agency_development
  pool: 5
  username: agenteo
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  encoding: unicode
  database: rental_agency_test
  pool: 5
  username: agenteo
  password:
